apiVersion: apps/v1             # Versión de kubernetes
kind: Deployment                # Tipo de Objeto 
metadata:                       # Información adicional
  name: grpcdeploy         # Nombre del despliegue
  labels:                       # Etiquetas con clave valor, sirven para identificar       
    app: grpcdeploy              # Etiqueta para el despliegue
spec:                           # Especificaciones del despliegue
  replicas: 1                   # Número de replicas que tendrá este pod
  selector:                     # Es la forma primitiva de hacer referencia, es como un id interno
    matchLabels:                # 
      app: grpcdeploy             # Etiqueta para que otros objetos de kubernetes lo encuentren
  template:                     # Es la configuración final del pod 
    metadata:                   # Tiene su propia metadata para la plantilla o pod
      labels:                   # 
        app: grpcdeploy          # Etiqueta del contenedor
    spec:                       # Tiene sus especificaciones
      containers:               # Información del contenedors o mas si el pod tiene muchos
      - name: grpcpubliser          # Nombre del contenedor
        image: gcr.io/omega-will-307406/grpcpubliser      # url de imagen, docker hub defautl
        ports:                  # puertos
        - containerPort: 2500   # puerto 80
      - name: grpcsuscriber          # Nombre del contenedor
        image: gcr.io/omega-will-307406/grpcsuscriber      # url de imagen, docker hub defautl
        ports:                  # puertos
        - containerPort: 4000   # puerto 80