version: '2'

services:

  mongo:
    container_name: mongo
    image: mongo:latest
    volumes:
      - ./dbdata:/dbdata
    restart: always

  mongoserver:  
    container_name: mongoserver
    image: mongoserver
    build: 
      context: ./
    ports:
        - '4000:4000'
    restart: always

  
